


(def_skys 
  texture_format
  "greecesky1"
  "sky1_farmland" 
  "sky1bluehills-a" 
  "sky2ssetsunsetdunes-a" 
  "sky2ssetsunsetdunes-b"
  "sky3"
  "sky6"
  "sky6mistymorn-a"
  "nuk_sky"
  "skycloudyblue")



(def_buildings
 "greeceship1"
 "greecetug"
 "greclighthouse"
 
 "ruinswall1"
 "ruinswall2"
 "ruinswall3"
 "ruinswall4"

 "ruinscorner"
 "ruinsonepillar"
 "ruinstwopillar"
 "ruinstwopillar2"
 "ruinstwoonly"
 "ruinsoneonly"
 "ruinsruin"
 "ruinsruin2"
 "ruinspad"

 "greecehouses1"
 "greecehouses2"
 "greecehouses3"

 "greecedockfull"
 "dockslant"

 "lawyerbuilding2x3"
 "bankbuilding3x3"
 "sphinxfull4x10"
 "templebigfull3x4"
 "mexistylelong1x3"
 "silobigfull2x2"
 "mainbasefull010698"
 "rockwallcorner"
 "rockwallend"
 "rockwallmid"
; "jerustemple1"
 "silowhole"
 "bridgebuilding" 
 "metalbridge"
 "iraq1"
 "iraqtallspacewhole"
 "iraqbentroofwhole"
 "building10yelo"
 "building1sq"
 "building1sqshort"
 "building3sqandhalfhigh"
 "building4highrise"
 "building6loadingdock"
 "building7mexico"
 "building8blueroof"
 "building9letterh"
 "buildorange2backdoors"
 "buildsmlbluewindows"
 "buildstonetemplebrwn"
 "builduglystuccolittlewin"
 "buildwarehouse1doortallcement"
 "buildwarehouse2garagedrslevels"
 "buildwarehouseloadingdock"
 "buildwarehousestuccobottom"
 "buld3sml2"
 "waterpumpbuild"
 "brickwall"
 "brickwallconcave"
 "brickwallcorner"
 "buildingarchswhite"
 "iraqtempl1whole"
 "building5lowrise"
 "building2squnderconst"
 "metalbridgepole"
 "barrerblock"
 "bridgebeam"
 "onelargecrate"
 "threelargecrates"
 "armycratebig"
 "armycratesml"
 "bridgebroken"
 "toilet"
 "oiltanksandwell"
 "oilwell"
 "palmtree1"
 "palmtree2"
 "palmtree3"
 "bridge1corner2"
 "bridge1middle2"
 "bridge1road2"
 "flag_golg"
 "flag_greece"
; "floorpad"
 "weaponpad"
; "bridgearch4"
 "bridgearchroad"
 "bridgebroken"
 "bridgebuilding"
; "drawbridge4"
; "drawbridgebuilding"
 "switzbridgehalf"
 "switzbridgezend2"
 "switzbridgezmid2"
 "switztunneleightlong"

 )

(set_default_ai "ai_joe")

(models
 object_format
 "greclighthouse_lod")