
//US Keyboard layout
VK_OEM_1		= ";"
VK_OEM_1_SHIFT	= ":"
VK_OEM_2		= "/"
VK_OEM_2_SHIFT	= "?"
VK_OEM_3		= "`"
VK_OEM_3_SHIFT	= "~"
VK_OEM_4		= "["
VK_OEM_4_SHIFT	= "{"
VK_OEM_5		= "]"
VK_OEM_6_SHIFT  = "}"
VK_OEM_7		= "APOSTROPHE"
VK_OEM_7_SHIFT	= "QUOTATION"
VK_OEM_8		= "UNAVAIL"
VK_OEM_8_SHIFT  = "UNAVAIL"
